package com.caili.pojo;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class DdmsMemberMaster {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddms_member_master.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddms_member_master.dist_no
     *
     * @mbg.generated
     */
    private String distNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddms_member_master.dist_name
     *
     * @mbg.generated
     */
    private String distName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddms_member_master.sponsor_no
     *
     * @mbg.generated
     */
    private String sponsorNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddms_member_master.sponsor_name
     *
     * @mbg.generated
     */
    private String sponsorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddms_member_master.level_no
     *
     * @mbg.generated
     */
    private Integer levelNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddms_member_master.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddms_member_master.pin
     *
     * @mbg.generated
     */
    private Byte pin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddms_member_master.telephone
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddms_member_master.dist_status
     *
     * @mbg.generated
     */
    private Byte distStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddms_member_master.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddms_member_master.vip_time
     *
     * @mbg.generated
     */
    private LocalDateTime vipTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddms_member_master.svip_time
     *
     * @mbg.generated
     */
    private LocalDateTime svipTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddms_member_master.id
     *
     * @return the value of ddms_member_master.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddms_member_master.id
     *
     * @param id the value for ddms_member_master.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddms_member_master.dist_no
     *
     * @return the value of ddms_member_master.dist_no
     *
     * @mbg.generated
     */
    public String getDistNo() {
        return distNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddms_member_master.dist_no
     *
     * @param distNo the value for ddms_member_master.dist_no
     *
     * @mbg.generated
     */
    public void setDistNo(String distNo) {
        this.distNo = distNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddms_member_master.dist_name
     *
     * @return the value of ddms_member_master.dist_name
     *
     * @mbg.generated
     */
    public String getDistName() {
        return distName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddms_member_master.dist_name
     *
     * @param distName the value for ddms_member_master.dist_name
     *
     * @mbg.generated
     */
    public void setDistName(String distName) {
        this.distName = distName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddms_member_master.sponsor_no
     *
     * @return the value of ddms_member_master.sponsor_no
     *
     * @mbg.generated
     */
    public String getSponsorNo() {
        return sponsorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddms_member_master.sponsor_no
     *
     * @param sponsorNo the value for ddms_member_master.sponsor_no
     *
     * @mbg.generated
     */
    public void setSponsorNo(String sponsorNo) {
        this.sponsorNo = sponsorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddms_member_master.sponsor_name
     *
     * @return the value of ddms_member_master.sponsor_name
     *
     * @mbg.generated
     */
    public String getSponsorName() {
        return sponsorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddms_member_master.sponsor_name
     *
     * @param sponsorName the value for ddms_member_master.sponsor_name
     *
     * @mbg.generated
     */
    public void setSponsorName(String sponsorName) {
        this.sponsorName = sponsorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddms_member_master.level_no
     *
     * @return the value of ddms_member_master.level_no
     *
     * @mbg.generated
     */
    public Integer getLevelNo() {
        return levelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddms_member_master.level_no
     *
     * @param levelNo the value for ddms_member_master.level_no
     *
     * @mbg.generated
     */
    public void setLevelNo(Integer levelNo) {
        this.levelNo = levelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddms_member_master.update_time
     *
     * @return the value of ddms_member_master.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddms_member_master.update_time
     *
     * @param updateTime the value for ddms_member_master.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddms_member_master.pin
     *
     * @return the value of ddms_member_master.pin
     *
     * @mbg.generated
     */
    public Byte getPin() {
        return pin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddms_member_master.pin
     *
     * @param pin the value for ddms_member_master.pin
     *
     * @mbg.generated
     */
    public void setPin(Byte pin) {
        this.pin = pin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddms_member_master.telephone
     *
     * @return the value of ddms_member_master.telephone
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddms_member_master.telephone
     *
     * @param telephone the value for ddms_member_master.telephone
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddms_member_master.dist_status
     *
     * @return the value of ddms_member_master.dist_status
     *
     * @mbg.generated
     */
    public Byte getDistStatus() {
        return distStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddms_member_master.dist_status
     *
     * @param distStatus the value for ddms_member_master.dist_status
     *
     * @mbg.generated
     */
    public void setDistStatus(Byte distStatus) {
        this.distStatus = distStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddms_member_master.add_time
     *
     * @return the value of ddms_member_master.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddms_member_master.add_time
     *
     * @param addTime the value for ddms_member_master.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddms_member_master.vip_time
     *
     * @return the value of ddms_member_master.vip_time
     *
     * @mbg.generated
     */
    public LocalDateTime getVipTime() {
        return vipTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddms_member_master.vip_time
     *
     * @param vipTime the value for ddms_member_master.vip_time
     *
     * @mbg.generated
     */
    public void setVipTime(LocalDateTime vipTime) {
        this.vipTime = vipTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddms_member_master.svip_time
     *
     * @return the value of ddms_member_master.svip_time
     *
     * @mbg.generated
     */
    public LocalDateTime getSvipTime() {
        return svipTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddms_member_master.svip_time
     *
     * @param svipTime the value for ddms_member_master.svip_time
     *
     * @mbg.generated
     */
    public void setSvipTime(LocalDateTime svipTime) {
        this.svipTime = svipTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddms_member_master
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", distNo=").append(distNo);
        sb.append(", distName=").append(distName);
        sb.append(", sponsorNo=").append(sponsorNo);
        sb.append(", sponsorName=").append(sponsorName);
        sb.append(", levelNo=").append(levelNo);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", pin=").append(pin);
        sb.append(", telephone=").append(telephone);
        sb.append(", distStatus=").append(distStatus);
        sb.append(", addTime=").append(addTime);
        sb.append(", vipTime=").append(vipTime);
        sb.append(", svipTime=").append(svipTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddms_member_master
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DdmsMemberMaster other = (DdmsMemberMaster) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDistNo() == null ? other.getDistNo() == null : this.getDistNo().equals(other.getDistNo()))
            && (this.getDistName() == null ? other.getDistName() == null : this.getDistName().equals(other.getDistName()))
            && (this.getSponsorNo() == null ? other.getSponsorNo() == null : this.getSponsorNo().equals(other.getSponsorNo()))
            && (this.getSponsorName() == null ? other.getSponsorName() == null : this.getSponsorName().equals(other.getSponsorName()))
            && (this.getLevelNo() == null ? other.getLevelNo() == null : this.getLevelNo().equals(other.getLevelNo()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getPin() == null ? other.getPin() == null : this.getPin().equals(other.getPin()))
            && (this.getTelephone() == null ? other.getTelephone() == null : this.getTelephone().equals(other.getTelephone()))
            && (this.getDistStatus() == null ? other.getDistStatus() == null : this.getDistStatus().equals(other.getDistStatus()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getVipTime() == null ? other.getVipTime() == null : this.getVipTime().equals(other.getVipTime()))
            && (this.getSvipTime() == null ? other.getSvipTime() == null : this.getSvipTime().equals(other.getSvipTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddms_member_master
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDistNo() == null) ? 0 : getDistNo().hashCode());
        result = prime * result + ((getDistName() == null) ? 0 : getDistName().hashCode());
        result = prime * result + ((getSponsorNo() == null) ? 0 : getSponsorNo().hashCode());
        result = prime * result + ((getSponsorName() == null) ? 0 : getSponsorName().hashCode());
        result = prime * result + ((getLevelNo() == null) ? 0 : getLevelNo().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getPin() == null) ? 0 : getPin().hashCode());
        result = prime * result + ((getTelephone() == null) ? 0 : getTelephone().hashCode());
        result = prime * result + ((getDistStatus() == null) ? 0 : getDistStatus().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getVipTime() == null) ? 0 : getVipTime().hashCode());
        result = prime * result + ((getSvipTime() == null) ? 0 : getSvipTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table ddms_member_master
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        distNo("dist_no", "distNo", "VARCHAR", false),
        distName("dist_name", "distName", "VARCHAR", false),
        sponsorNo("sponsor_no", "sponsorNo", "VARCHAR", false),
        sponsorName("sponsor_name", "sponsorName", "VARCHAR", false),
        levelNo("level_no", "levelNo", "INTEGER", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        pin("pin", "pin", "TINYINT", false),
        telephone("telephone", "telephone", "VARCHAR", false),
        distStatus("dist_status", "distStatus", "TINYINT", false),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        vipTime("vip_time", "vipTime", "TIMESTAMP", false),
        svipTime("svip_time", "svipTime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ddms_member_master
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ddms_member_master
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ddms_member_master
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ddms_member_master
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ddms_member_master
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ddms_member_master
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddms_member_master
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddms_member_master
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddms_member_master
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddms_member_master
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddms_member_master
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddms_member_master
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddms_member_master
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddms_member_master
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddms_member_master
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ddms_member_master
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}